export const SUBMIT_LOGIN_FORM = 'SUBMIT_LOGIN_FORM';
export const CLEAR_LOGIN = 'CLEAR_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const HANDLE_LOGIN_INPUT = 'HANDLE_LOGIN_INPUT';
export const INPUT_VALIDATION_FAILURE = 'INPUT_VALIDATION_FAILURE';
export const INPUT_VALIDATION_SUCCESS = 'INPUT_VALIDATION_SUCCESS';
