export const SIGNUP_FORM = 'SIGNUP_FORM';
export const SIGNUP_FORM_SUBMIT = 'SIGNUP_FORM_SUBMIT';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const CLEAR_SIGNUP_FORM = 'CLEAR_SIGNUP_FORM';
